from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


def create_report(filename, patient_name, disease, result, confidence, suggestions):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>AI Health Assistant Report</b>", styles["Title"]))

    story.append(Paragraph(f"<b>Patient Name:</b> {patient_name}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Disease:</b> {disease}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Prediction:</b> {result}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Model Confidence:</b> {confidence:.2f}%", styles["BodyText"]))

    story.append(Paragraph("<br/><b>Health Suggestions</b>", styles["Heading2"]))

    for item in suggestions:
        story.append(Paragraph(f"• {item}", styles["BodyText"]))

    story.append(Paragraph("<br/>Generated by AI Health Assistant", styles["Italic"]))

    doc.build(story)